<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class NECSeeder extends Seeder
{
    public function run()
    {
        $data_nec_broad = [
            ['nb_id' => '1',      'nb_code' => '00',       'nb_name' => 'Generic programmes an qualifications'],
            ['nb_id' => '2',      'nb_code' => '01',       'nb_name' => 'Education'],
            ['nb_id' => '3',      'nb_code' => '02',       'nb_name' => 'Arts and humanities'],
            ['nb_id' => '4',      'nb_code' => '03',       'nb_name' => 'Social sciences, journalism and information'],
            ['nb_id' => '5',      'nb_code' => '04',       'nb_name' => 'Business, administration and law'],
            ['nb_id' => '6',      'nb_code' => '05',       'nb_name' => 'Natural sciences, mathematics and statistics'],
            ['nb_id' => '7',      'nb_code' => '06',       'nb_name' => 'Information and communication technologies'],
            ['nb_id' => '8',      'nb_code' => '07',       'nb_name' => 'Engineering, manufacturing and construction'],
            ['nb_id' => '9',      'nb_code' => '08',       'nb_name' => 'Agriculture, forestry, fisheries and veterinary'],
            ['nb_id' => '10',     'nb_code' => '09',       'nb_name' => 'Health and welfare'],
            ['nb_id' => '11',     'nb_code' => '10',       'nb_name' => 'Services'],
            ['nb_id' => '12',     'nb_code' => '99',       'nb_name' => 'Unknown or unspecified']
        ];

        $this->db->table('qvc_upsi.nec_broad')->insertBatch($data_nec_broad);

        $data_nec_narrow = [

            ['nn_id' => '1',  'nn_nb_id' => '1',  'nn_code' => '000', 'nn_name' => 'Generic programmes and qualifications not further defined'],
            ['nn_id' => '2',  'nn_nb_id' => '1',  'nn_code' => '001', 'nn_name' => 'Basic programmes and qualifications'],
            ['nn_id' => '3',  'nn_nb_id' => '1',  'nn_code' => '002', 'nn_name' => 'Literacy and numeracy'],
            ['nn_id' => '4',  'nn_nb_id' => '1',  'nn_code' => '003', 'nn_name' => 'Personal skills'],
            ['nn_id' => '5',  'nn_nb_id' => '1',  'nn_code' => '009', 'nn_name' => 'Generic programmes and qualifications not elsewhere classified'],
            ['nn_id' => '6',  'nn_nb_id' => '2',  'nn_code' => '011', 'nn_name' => 'Education'],
            ['nn_id' => '7',  'nn_nb_id' => '2',  'nn_code' => '018', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving education'],
            ['nn_id' => '8',  'nn_nb_id' => '3',  'nn_code' => '020', 'nn_name' => 'Arts and humanities not further defined'],
            ['nn_id' => '9',  'nn_nb_id' => '3',  'nn_code' => '021', 'nn_name' => 'Arts'],
            ['nn_id' => '10', 'nn_nb_id' => '3',  'nn_code' => '022', 'nn_name' => 'Humanities (except languages)'],
            ['nn_id' => '11', 'nn_nb_id' => '3',  'nn_code' => '023', 'nn_name' => 'Languages'],
            ['nn_id' => '12', 'nn_nb_id' => '3',  'nn_code' => '028', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving arts and humanities'],
            ['nn_id' => '13', 'nn_nb_id' => '3',  'nn_code' => '029', 'nn_name' => 'Arts and humanities not else classified'],
            ['nn_id' => '14', 'nn_nb_id' => '4',  'nn_code' => '030', 'nn_name' => 'Social sciences, journalism and information not further defined'],
            ['nn_id' => '15', 'nn_nb_id' => '4',  'nn_code' => '031', 'nn_name' => 'Social and behavioural sciences'],
            ['nn_id' => '16', 'nn_nb_id' => '4',  'nn_code' => '032', 'nn_name' => 'Journalism, information and communication'],
            ['nn_id' => '17', 'nn_nb_id' => '4',  'nn_code' => '038', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information'],
            ['nn_id' => '18', 'nn_nb_id' => '4',  'nn_code' => '039', 'nn_name' => 'Social sciences, journalism and information not elsewhere classified'],
            ['nn_id' => '19', 'nn_nb_id' => '5',  'nn_code' => '040', 'nn_name' => 'Business, administration and law not further defined'],
            ['nn_id' => '20', 'nn_nb_id' => '5',  'nn_code' => '041', 'nn_name' => 'Business and management'],
            ['nn_id' => '21', 'nn_nb_id' => '5',  'nn_code' => '042', 'nn_name' => 'Law'],
            ['nn_id' => '22', 'nn_nb_id' => '5',  'nn_code' => '048', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving business, administration and law'],
            ['nn_id' => '23', 'nn_nb_id' => '5',  'nn_code' => '049', 'nn_name' => 'Business, administration and law not elsewhere classified'],
            ['nn_id' => '24', 'nn_nb_id' => '6',  'nn_code' => '050', 'nn_name' => 'Natural sciences, mathematics and statistics not further defined'],
            ['nn_id' => '25', 'nn_nb_id' => '6',  'nn_code' => '051', 'nn_name' => 'Biological and related sciences'],
            ['nn_id' => '26', 'nn_nb_id' => '6',  'nn_code' => '052', 'nn_name' => 'Environment'],
            ['nn_id' => '27', 'nn_nb_id' => '6',  'nn_code' => '053', 'nn_name' => 'Physical sciences'],
            ['nn_id' => '28', 'nn_nb_id' => '6',  'nn_code' => '054', 'nn_name' => 'Mathematics and statistics'],
            ['nn_id' => '29', 'nn_nb_id' => '6',  'nn_code' => '058', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics'],
            ['nn_id' => '30', 'nn_nb_id' => '6',  'nn_code' => '059', 'nn_name' => 'Natural sciences, mathematics and statistics not elsewhere classified'],
            ['nn_id' => '31', 'nn_nb_id' => '7',  'nn_code' => '061', 'nn_name' => 'Information and communication technologies'],
            ['nn_id' => '32', 'nn_nb_id' => '7',  'nn_code' => '068', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving information and communication technologies'],
            ['nn_id' => '33', 'nn_nb_id' => '8',  'nn_code' => '070', 'nn_name' => 'Engineering, manufacturing and construction not further defined'],
            ['nn_id' => '34', 'nn_nb_id' => '8',  'nn_code' => '071', 'nn_name' => 'Engineering and engineering trades'],
            ['nn_id' => '35', 'nn_nb_id' => '8',  'nn_code' => '072', 'nn_name' => 'Manufacturing and processing'],
            ['nn_id' => '36', 'nn_nb_id' => '8',  'nn_code' => '073', 'nn_name' => 'Architecture, surveying and town planning'],
            ['nn_id' => '37', 'nn_nb_id' => '8',  'nn_code' => '074', 'nn_name' => 'Engineering technology'],
            ['nn_id' => '38', 'nn_nb_id' => '8',  'nn_code' => '078', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction'],
            ['nn_id' => '39', 'nn_nb_id' => '8',  'nn_code' => '079', 'nn_name' => 'Engineering, manufacturing and construction not elsewhere classified'],
            ['nn_id' => '40', 'nn_nb_id' => '9',  'nn_code' => '080', 'nn_name' => 'Agriculture, forestry, fisheries and veterinary not further defined'],
            ['nn_id' => '41', 'nn_nb_id' => '9',  'nn_code' => '081', 'nn_name' => 'Agriculture'],
            ['nn_id' => '42', 'nn_nb_id' => '9',  'nn_code' => '082', 'nn_name' => 'Forestry'],
            ['nn_id' => '43', 'nn_nb_id' => '9',  'nn_code' => '083', 'nn_name' => 'Fisheries'],
            ['nn_id' => '44', 'nn_nb_id' => '9',  'nn_code' => '084', 'nn_name' => 'Veterinary'],
            ['nn_id' => '45', 'nn_nb_id' => '9',  'nn_code' => '088', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary'],
            ['nn_id' => '46', 'nn_nb_id' => '9',  'nn_code' => '089', 'nn_name' => 'Agriculture, forestry, fisheries and veterinary not elsewhere classified'],
            ['nn_id' => '47', 'nn_nb_id' => '10', 'nn_code' => '090', 'nn_name' => 'Health and welfare not further defined'],
            ['nn_id' => '48', 'nn_nb_id' => '10', 'nn_code' => '091', 'nn_name' => 'Health'],
            ['nn_id' => '49', 'nn_nb_id' => '10', 'nn_code' => '092', 'nn_name' => 'Welfare'],
            ['nn_id' => '50', 'nn_nb_id' => '10', 'nn_code' => '098', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving health and welfare'],
            ['nn_id' => '51', 'nn_nb_id' => '10', 'nn_code' => '099', 'nn_name' => 'Health and welfare not elsewhere classified'],
            ['nn_id' => '52', 'nn_nb_id' => '11', 'nn_code' => '100', 'nn_name' => 'Services not further defined'],
            ['nn_id' => '53', 'nn_nb_id' => '11', 'nn_code' => '101', 'nn_name' => 'Personal services'],
            ['nn_id' => '54', 'nn_nb_id' => '11', 'nn_code' => '102', 'nn_name' => 'Hygine and occupational health services'],
            ['nn_id' => '55', 'nn_nb_id' => '11', 'nn_code' => '103', 'nn_name' => 'Security services'],
            ['nn_id' => '56', 'nn_nb_id' => '11', 'nn_code' => '104', 'nn_name' => 'Transport services'],
            ['nn_id' => '57', 'nn_nb_id' => '11', 'nn_code' => '108', 'nn_name' => 'Inter-disciplinary programmes and qualifications involving services'],
            ['nn_id' => '58', 'nn_nb_id' => '11', 'nn_code' => '109', 'nn_name' => 'Services not elsewhere classified'],
            ['nn_id' => '59', 'nn_nb_id' => '12', 'nn_code' => '999', 'nn_name' => 'Field unknown'],

        ];

        $this->db->table('qvc_upsi.nec_narrow')->insertBatch($data_nec_narrow);

        $data_nec_detail = [
            ['nd_id' => '1', 'nd_nn_id' => '1', 'nd_code' => '0000', 'nd_name' => 'Generic programmes and qualifications not further defined'],
            ['nd_id' => '2', 'nd_nn_id' => '2', 'nd_code' => '0011', 'nd_name' => 'Basic programmes and qualifications'],
            ['nd_id' => '3', 'nd_nn_id' => '3', 'nd_code' => '0021', 'nd_name' => 'Literacy and numeracy'],
            ['nd_id' => '4', 'nd_nn_id' => '4', 'nd_code' => '0031', 'nd_name' => 'Personal skills'],
            ['nd_id' => '5', 'nd_nn_id' => '5', 'nd_code' => '0099', 'nd_name' => 'Generic programmes and qualifications not elsewhere classified'],
            ['nd_id' => '6', 'nd_nn_id' => '6', 'nd_code' => '0110', 'nd_name' => 'Education not further defined'],
            ['nd_id' => '7', 'nd_nn_id' => '6', 'nd_code' => '0111', 'nd_name' => 'Education science'],
            ['nd_id' => '8', 'nd_nn_id' => '6', 'nd_code' => '0112', 'nd_name' => 'Training for pre-school teachers'],
            ['nd_id' => '9', 'nd_nn_id' => '6', 'nd_code' => '0113', 'nd_name' => 'Educator training without subject specialisation'],
            ['nd_id' => '10', 'nd_nn_id' => '6', 'nd_code' => '0114', 'nd_name' => 'Educator training with subject specialisation'],
            ['nd_id' => '11', 'nd_nn_id' => '6', 'nd_code' => '0119', 'nd_name' => 'Programmes and qualifications involving education not elsewhere classified'],
            ['nd_id' => '12', 'nd_nn_id' => '7', 'nd_code' => '0188', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving education'],
            ['nd_id' => '13', 'nd_nn_id' => '8', 'nd_code' => '0200', 'nd_name' => 'Arts and humanities not further defined'],
            ['nd_id' => '14', 'nd_nn_id' => '9', 'nd_code' => '0210', 'nd_name' => 'Arts not further defined'],
            ['nd_id' => '15', 'nd_nn_id' => '9', 'nd_code' => '0211', 'nd_name' => 'Audio-visual techniques and media production'],
            ['nd_id' => '16', 'nd_nn_id' => '9', 'nd_code' => '0212', 'nd_name' => 'Fashion, interior and industrial design'],
            ['nd_id' => '17', 'nd_nn_id' => '9', 'nd_code' => '0213', 'nd_name' => 'Fine arts'],
            ['nd_id' => '18', 'nd_nn_id' => '9', 'nd_code' => '0214', 'nd_name' => 'Craft skills'],
            ['nd_id' => '19', 'nd_nn_id' => '9', 'nd_code' => '0215', 'nd_name' => 'Music and performing arts'],
            ['nd_id' => '20', 'nd_nn_id' => '9', 'nd_code' => '0216', 'nd_name' => 'Film, television and screen studies'],
            ['nd_id' => '21', 'nd_nn_id' => '9', 'nd_code' => '0219', 'nd_name' => 'Arts not elsewhere classified'],
            ['nd_id' => '22', 'nd_nn_id' => '10', 'nd_code' => '0220', 'nd_name' => 'Humanities (except languages) not further defined'],
            ['nd_id' => '23', 'nd_nn_id' => '10', 'nd_code' => '0221', 'nd_name' => 'Religion and technology'],
            ['nd_id' => '24', 'nd_nn_id' => '10', 'nd_code' => '0222', 'nd_name' => 'History and archaeology'],
            ['nd_id' => '25', 'nd_nn_id' => '10', 'nd_code' => '0223', 'nd_name' => 'Philosophy and ethics'],
            ['nd_id' => '26', 'nd_nn_id' => '10', 'nd_code' => '0224', 'nd_name' => 'Islamic studies'],
            ['nd_id' => '27', 'nd_nn_id' => '10', 'nd_code' => '0229', 'nd_name' => 'Humanities (except languages) not elsewhere classified'],
            ['nd_id' => '28', 'nd_nn_id' => '11', 'nd_code' => '0230', 'nd_name' => 'Languages not further defined'],
            ['nd_id' => '29', 'nd_nn_id' => '11', 'nd_code' => '0231', 'nd_name' => 'Language acquisition'],
            ['nd_id' => '30', 'nd_nn_id' => '11', 'nd_code' => '0232', 'nd_name' => 'Literature and linguistics'],
            ['nd_id' => '31', 'nd_nn_id' => '11', 'nd_code' => '0233', 'nd_name' => 'National language'],
            ['nd_id' => '32', 'nd_nn_id' => '11', 'nd_code' => '0239', 'nd_name' => 'Languages not elsewhere classified'],
            ['nd_id' => '33', 'nd_nn_id' => '12', 'nd_code' => '0288', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving arts and humanities'],
            ['nd_id' => '34', 'nd_nn_id' => '13', 'nd_code' => '0299', 'nd_name' => 'Arts and humanities not elsewhere classified'],
            ['nd_id' => '35', 'nd_nn_id' => '14', 'nd_code' => '0300', 'nd_name' => 'Social sciences, journalism and information not further defined'],
            ['nd_id' => '36', 'nd_nn_id' => '15', 'nd_code' => '0310', 'nd_name' => 'Social and behavioural sciences not further defined'],
            ['nd_id' => '37', 'nd_nn_id' => '15', 'nd_code' => '0311', 'nd_name' => 'Economics'],
            ['nd_id' => '38', 'nd_nn_id' => '15', 'nd_code' => '0312', 'nd_name' => 'Political sciences and public policy'],
            ['nd_id' => '39', 'nd_nn_id' => '15', 'nd_code' => '0313', 'nd_name' => 'Psychology'],
            ['nd_id' => '40', 'nd_nn_id' => '15', 'nd_code' => '0314', 'nd_name' => 'Sociology and cultural studies'],
            ['nd_id' => '41', 'nd_nn_id' => '15', 'nd_code' => '0319', 'nd_name' => 'Social and behavioural sciences not elsewhere classified'],
            ['nd_id' => '42', 'nd_nn_id' => '16', 'nd_code' => '0320', 'nd_name' => 'Journalism, information and communication not further defined'],
            ['nd_id' => '43', 'nd_nn_id' => '16', 'nd_code' => '0321', 'nd_name' => 'Journalism and reporting'],
            ['nd_id' => '44', 'nd_nn_id' => '16', 'nd_code' => '0322', 'nd_name' => 'Library, information and archival studies'],
            ['nd_id' => '45', 'nd_nn_id' => '16', 'nd_code' => '0323', 'nd_name' => 'Media and communication'],
            ['nd_id' => '46', 'nd_nn_id' => '16', 'nd_code' => '0329', 'nd_name' => 'Journalism, information and communication not elsewhere classified'],
            ['nd_id' => '47', 'nd_nn_id' => '17', 'nd_code' => '0388', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving social sciences, journalism and information'],
            ['nd_id' => '48', 'nd_nn_id' => '18', 'nd_code' => '0399', 'nd_name' => 'Social sciences, journalism and information not elsewhere classified'],
            ['nd_id' => '49', 'nd_nn_id' => '19', 'nd_code' => '0400', 'nd_name' => 'Business, administration and law not further defined'],
            ['nd_id' => '50', 'nd_nn_id' => '20', 'nd_code' => '0410', 'nd_name' => 'Business and administration not further defined'],
            ['nd_id' => '51', 'nd_nn_id' => '20', 'nd_code' => '0411', 'nd_name' => 'Accounting, auditing and taxation'],
            ['nd_id' => '52', 'nd_nn_id' => '20', 'nd_code' => '0412', 'nd_name' => 'Finance, banking and insurance'],
            ['nd_id' => '53', 'nd_nn_id' => '20', 'nd_code' => '0413', 'nd_name' => 'Islamic banking and finance'],
            ['nd_id' => '54', 'nd_nn_id' => '20', 'nd_code' => '0414', 'nd_name' => 'Management and administration'],
            ['nd_id' => '55', 'nd_nn_id' => '20', 'nd_code' => '0415', 'nd_name' => 'Marketing and advertising'],
            ['nd_id' => '56', 'nd_nn_id' => '20', 'nd_code' => '0416', 'nd_name' => 'Secretarial and office studies'],
            ['nd_id' => '57', 'nd_nn_id' => '20', 'nd_code' => '0417', 'nd_name' => 'Work skills'],
            ['nd_id' => '58', 'nd_nn_id' => '20', 'nd_code' => '0419', 'nd_name' => 'Business and administration not elsewhere classified'],
            ['nd_id' => '59', 'nd_nn_id' => '21', 'nd_code' => '0421', 'nd_name' => 'Law'],
            ['nd_id' => '60', 'nd_nn_id' => '22', 'nd_code' => '0488', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving business, administration and law'],
            ['nd_id' => '61', 'nd_nn_id' => '23', 'nd_code' => '0499', 'nd_name' => 'Business, administration and law not elsewhere classified'],
            ['nd_id' => '62', 'nd_nn_id' => '24', 'nd_code' => '0500', 'nd_name' => 'Natural sciences, mathematics and statistics not further defined'],
            ['nd_id' => '63', 'nd_nn_id' => '25', 'nd_code' => '0510', 'nd_name' => 'Biological and related sciences not further defined'],
            ['nd_id' => '64', 'nd_nn_id' => '25', 'nd_code' => '0511', 'nd_name' => 'Biology'],
            ['nd_id' => '65', 'nd_nn_id' => '25', 'nd_code' => '0512', 'nd_name' => 'Biochemistry'],
            ['nd_id' => '66', 'nd_nn_id' => '25', 'nd_code' => '0519', 'nd_name' => 'Biological and related sciences not elsewhere classified'],
            ['nd_id' => '67', 'nd_nn_id' => '26', 'nd_code' => '0520', 'nd_name' => 'Environment not further defined'],
            ['nd_id' => '68', 'nd_nn_id' => '26', 'nd_code' => '0521', 'nd_name' => 'Environmental sciences'],
            ['nd_id' => '69', 'nd_nn_id' => '26', 'nd_code' => '0522', 'nd_name' => 'Natural environments and wildlife'],
            ['nd_id' => '70', 'nd_nn_id' => '26', 'nd_code' => '0529', 'nd_name' => 'Environment not elsewhere classified'],
            ['nd_id' => '71', 'nd_nn_id' => '27', 'nd_code' => '0530', 'nd_name' => 'Physical sciences not further defined'],
            ['nd_id' => '72', 'nd_nn_id' => '27', 'nd_code' => '0531', 'nd_name' => 'Chemistry'],
            ['nd_id' => '73', 'nd_nn_id' => '27', 'nd_code' => '0532', 'nd_name' => 'Earth sciences'],
            ['nd_id' => '74', 'nd_nn_id' => '27', 'nd_code' => '0533', 'nd_name' => 'Physics'],
            ['nd_id' => '75', 'nd_nn_id' => '27', 'nd_code' => '0539', 'nd_name' => 'Physical sciences not elsewhere classified'],
            ['nd_id' => '76', 'nd_nn_id' => '28', 'nd_code' => '0540', 'nd_name' => 'Mathematics and statistics not further defined'],
            ['nd_id' => '77', 'nd_nn_id' => '28', 'nd_code' => '0541', 'nd_name' => 'Mathematics'],
            ['nd_id' => '78', 'nd_nn_id' => '28', 'nd_code' => '0542', 'nd_name' => 'Statistics'],
            ['nd_id' => '79', 'nd_nn_id' => '29', 'nd_code' => '0588', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving natural sciences, mathematics and statistics'],
            ['nd_id' => '80',  'nd_nn_id' => '30', 'nd_code' => '0599', 'nd_name' => 'Natural sciences, mathematics and statistics not elsewhere classified'],
            ['nd_id' => '81',  'nd_nn_id' => '31', 'nd_code' => '0610', 'nd_name' => 'Information and communication technologies (ICTs) not further defined'],
            ['nd_id' => '82',  'nd_nn_id' => '31', 'nd_code' => '0611', 'nd_name' => 'Information technology and information system'],
            ['nd_id' => '83',  'nd_nn_id' => '31', 'nd_code' => '0612', 'nd_name' => 'Software engineering'],
            ['nd_id' => '84',  'nd_nn_id' => '31', 'nd_code' => '0613', 'nd_name' => 'Computer science'],
            ['nd_id' => '85',  'nd_nn_id' => '31', 'nd_code' => '0614', 'nd_name' => 'Computer use'],
            ['nd_id' => '86',  'nd_nn_id' => '31', 'nd_code' => '0619', 'nd_name' => 'Information and communication technologies (ICTs) not elsewhere classified'],
            ['nd_id' => '87',  'nd_nn_id' => '32', 'nd_code' => '0688', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving information and communication technologies'],
            ['nd_id' => '88',  'nd_nn_id' => '33', 'nd_code' => '0700', 'nd_name' => 'Engineering, manufacturing and construction not further defined'],
            ['nd_id' => '89',  'nd_nn_id' => '34', 'nd_code' => '0710', 'nd_name' => 'Engineering and engineering trades not further defined'],
            ['nd_id' => '90',  'nd_nn_id' => '34', 'nd_code' => '0711', 'nd_name' => 'Chemical engineering and processes'],
            ['nd_id' => '91',  'nd_nn_id' => '34', 'nd_code' => '0712', 'nd_name' => 'Electricity and energy'],
            ['nd_id' => '92',  'nd_nn_id' => '34', 'nd_code' => '0713', 'nd_name' => 'Electronics and automation'],
            ['nd_id' => '93',  'nd_nn_id' => '34', 'nd_code' => '0714', 'nd_name' => 'Mechanics and metal trades'],
            ['nd_id' => '94',  'nd_nn_id' => '34', 'nd_code' => '0715', 'nd_name' => 'Motor vehicles, ships and aircraft'],
            ['nd_id' => '95',  'nd_nn_id' => '34', 'nd_code' => '0716', 'nd_name' => 'Civil engineering'],
            ['nd_id' => '96',  'nd_nn_id' => '34', 'nd_code' => '0717', 'nd_name' => 'Environmental protection technology'],
            ['nd_id' => '97',  'nd_nn_id' => '34', 'nd_code' => '0719', 'nd_name' => 'Engineering and engineering trades not elsewhere classified'],
            ['nd_id' => '98',  'nd_nn_id' => '35', 'nd_code' => '0720', 'nd_name' => 'Manufacturing and processing not further defined'],
            ['nd_id' => '99',  'nd_nn_id' => '35', 'nd_code' => '0721', 'nd_name' => 'Food processing'],
            ['nd_id' => '100', 'nd_nn_id' => '35', 'nd_code' => '0722', 'nd_name' => 'Materials (glass, paper, plastic and wood)'],
            ['nd_id' => '101', 'nd_nn_id' => '35', 'nd_code' => '0723', 'nd_name' => 'Textiles (clothes, footwear and leather)'],
            ['nd_id' => '102', 'nd_nn_id' => '35', 'nd_code' => '0724', 'nd_name' => 'Mining and extraction'],
            ['nd_id' => '103', 'nd_nn_id' => '35', 'nd_code' => '0729', 'nd_name' => 'Manufacturing and processing not elsewhere classified'],
            ['nd_id' => '104', 'nd_nn_id' => '36', 'nd_code' => '0730', 'nd_name' => 'Architecture, surveying and town planning not further defined'],
            ['nd_id' => '105', 'nd_nn_id' => '36', 'nd_code' => '0731', 'nd_name' => 'Architecture'],
            ['nd_id' => '106', 'nd_nn_id' => '36', 'nd_code' => '0732', 'nd_name' => 'Urban and regional planning'],
            ['nd_id' => '107', 'nd_nn_id' => '36', 'nd_code' => '0733', 'nd_name' => 'Building and construction'],
            ['nd_id' => '108', 'nd_nn_id' => '36', 'nd_code' => '0734', 'nd_name' => 'Surveying'],
            ['nd_id' => '109', 'nd_nn_id' => '37', 'nd_code' => '0741', 'nd_name' => 'Engineering technology'],
            ['nd_id' => '110', 'nd_nn_id' => '38', 'nd_code' => '0788', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving engineering, manufacturing and construction'],
            ['nd_id' => '111', 'nd_nn_id' => '39', 'nd_code' => '0799', 'nd_name' => 'Engineering, manufacturing and construction not elsewhere classified'],
            ['nd_id' => '112', 'nd_nn_id' => '40', 'nd_code' => '0800', 'nd_name' => 'Agriculture. forestry, fisheries and veterinary not further defined'],
            ['nd_id' => '113', 'nd_nn_id' => '41', 'nd_code' => '0810', 'nd_name' => 'Agriculture not further defined'],
            ['nd_id' => '114', 'nd_nn_id' => '41', 'nd_code' => '0811', 'nd_name' => 'Crop and livestock production'],
            ['nd_id' => '115', 'nd_nn_id' => '41', 'nd_code' => '0812', 'nd_name' => 'Horticulture'],
            ['nd_id' => '116', 'nd_nn_id' => '41', 'nd_code' => '0819', 'nd_name' => 'Agriculture not elsewhere classified'],
            ['nd_id' => '117', 'nd_nn_id' => '42', 'nd_code' => '0821', 'nd_name' => 'Forestry'],
            ['nd_id' => '118', 'nd_nn_id' => '43', 'nd_code' => '0831', 'nd_name' => 'Fisheries'],
            ['nd_id' => '119', 'nd_nn_id' => '44', 'nd_code' => '0841', 'nd_name' => 'Veterinary'],
            ['nd_id' => '120', 'nd_nn_id' => '45', 'nd_code' => '0888', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving agriculture, forestry, fisheries and veterinary'],
            ['nd_id' => '121', 'nd_nn_id' => '46', 'nd_code' => '0899', 'nd_name' => 'Agriculture, forestry, fisheries and veterinary not elsewhere classified'],
            ['nd_id' => '122', 'nd_nn_id' => '47', 'nd_code' => '0900', 'nd_name' => 'Health and welfare not further defined'],
            ['nd_id' => '123', 'nd_nn_id' => '48', 'nd_code' => '0910', 'nd_name' => 'Health not further defined'],
            ['nd_id' => '124', 'nd_nn_id' => '48', 'nd_code' => '0911', 'nd_name' => 'Dental studies'],
            ['nd_id' => '125', 'nd_nn_id' => '48', 'nd_code' => '0912', 'nd_name' => 'Medicine'],
            ['nd_id' => '126', 'nd_nn_id' => '48', 'nd_code' => '0913', 'nd_name' => 'Nursing, midwifery and medical assistance'],
            ['nd_id' => '127', 'nd_nn_id' => '48', 'nd_code' => '0914', 'nd_name' => 'Medical diagnostic and treatment technology'],
            ['nd_id' => '128', 'nd_nn_id' => '48', 'nd_code' => '0915', 'nd_name' => 'Therapy and rehabilitation'],
            ['nd_id' => '129', 'nd_nn_id' => '48', 'nd_code' => '0916', 'nd_name' => 'Pharmacy'],
            ['nd_id' => '130', 'nd_nn_id' => '48', 'nd_code' => '0917', 'nd_name' => 'Traditional and complementary medicine and therapy'],
            ['nd_id' => '131', 'nd_nn_id' => '48', 'nd_code' => '0919', 'nd_name' => 'Health not elsewhere classified'],
            ['nd_id' => '132', 'nd_nn_id' => '49', 'nd_code' => '0920', 'nd_name' => 'Welfare not further defined'],
            ['nd_id' => '133', 'nd_nn_id' => '49', 'nd_code' => '0921', 'nd_name' => 'Care of elderly and of disabled adults'],
            ['nd_id' => '134', 'nd_nn_id' => '49', 'nd_code' => '0922', 'nd_name' => 'Child care and youth services'],
            ['nd_id' => '135', 'nd_nn_id' => '49', 'nd_code' => '0923', 'nd_name' => 'Social work and counseling'],
            ['nd_id' => '136', 'nd_nn_id' => '49', 'nd_code' => '0929', 'nd_name' => 'Welfare not elsewhere classified'],
            ['nd_id' => '137', 'nd_nn_id' => '50', 'nd_code' => '0988', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving health and welfare'],
            ['nd_id' => '138', 'nd_nn_id' => '51', 'nd_code' => '0999', 'nd_name' => 'Health and welfare not elsewhere classified'],
            ['nd_id' => '139', 'nd_nn_id' => '52', 'nd_code' => '1000', 'nd_name' => 'Services not further defined'],
            ['nd_id' => '140', 'nd_nn_id' => '53', 'nd_code' => '1010', 'nd_name' => 'Personal services nor further defined'],
            ['nd_id' => '141', 'nd_nn_id' => '53', 'nd_code' => '1011', 'nd_name' => 'Domestic services'],
            ['nd_id' => '142', 'nd_nn_id' => '53', 'nd_code' => '1012', 'nd_name' => 'Hair and beauty services'],
            ['nd_id' => '143', 'nd_nn_id' => '53', 'nd_code' => '1013', 'nd_name' => 'Hotel, restaurants and catering'],
            ['nd_id' => '144', 'nd_nn_id' => '53', 'nd_code' => '1014', 'nd_name' => 'Sports'],
            ['nd_id' => '145', 'nd_nn_id' => '53', 'nd_code' => '1015', 'nd_name' => 'Travel, tourism and leisure'],
            ['nd_id' => '146', 'nd_nn_id' => '53', 'nd_code' => '1019', 'nd_name' => 'Personal services not elsewhere classified'],
            ['nd_id' => '147', 'nd_nn_id' => '54', 'nd_code' => '1020', 'nd_name' => 'Hygine and occupational health services not further defined'],
            ['nd_id' => '148', 'nd_nn_id' => '54', 'nd_code' => '1021', 'nd_name' => 'Community sanitation'],
            ['nd_id' => '149', 'nd_nn_id' => '54', 'nd_code' => '1022', 'nd_name' => 'Occupational health and safety'],
            ['nd_id' => '150', 'nd_nn_id' => '54', 'nd_code' => '1029', 'nd_name' => 'Hygine and occupational health services not elsewhere classified'],
            ['nd_id' => '151', 'nd_nn_id' => '55', 'nd_code' => '1030', 'nd_name' => 'Security services not further defined'],
            ['nd_id' => '152', 'nd_nn_id' => '55', 'nd_code' => '1031', 'nd_name' => 'Military and defence'],
            ['nd_id' => '153', 'nd_nn_id' => '55', 'nd_code' => '1032', 'nd_name' => 'Protection of persons and property'],
            ['nd_id' => '154', 'nd_nn_id' => '55', 'nd_code' => '1039', 'nd_name' => 'Security services not elsewhere classified'],
            ['nd_id' => '155', 'nd_nn_id' => '56', 'nd_code' => '1041', 'nd_name' => 'Transport services'],
            ['nd_id' => '156', 'nd_nn_id' => '57', 'nd_code' => '1088', 'nd_name' => 'Inter-disciplinary programmes and qualifications involving services'],
            ['nd_id' => '157', 'nd_nn_id' => '58', 'nd_code' => '1099', 'nd_name' => 'Services not elsewhere classified'],
            ['nd_id' => '158', 'nd_nn_id' => '59', 'nd_code' => '9999', 'nd_name' => 'Field unknown'],

        ];

        $this->db->table('qvc_upsi.nec_detail')->insertBatch($data_nec_detail);
    }
}
